-- Run this entire file once in Supabase Dashboard > SQL Editor.
-- Then create your private admin user in Authentication > Users.

create schema if not exists private;

create table if not exists public.profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  role text not null default 'editor' check (role in ('editor','admin')),
  display_name text,
  created_at timestamptz not null default now()
);

create table if not exists public.stories (
  id bigint generated by default as identity primary key,
  slug text not null unique check (slug ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'),
  title text not null,
  dek text not null,
  country text not null,
  city text not null,
  section text not null,
  author text not null,
  body jsonb not null default '[]'::jsonb,
  status text not null default 'draft' check (status in ('draft','published')),
  published_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  featured_rank integer check (featured_rank is null or featured_rank > 0),
  created_by uuid references auth.users(id)
);

create table if not exists public.page_views (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  path text not null,
  story_slug text,
  referrer text,
  session_id text
);

create table if not exists public.support_tickets (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  name text not null check (char_length(name) between 1 and 120),
  email text not null check (char_length(email) between 3 and 320),
  subject text not null check (char_length(subject) between 1 and 180),
  message text not null check (char_length(message) between 10 and 10000),
  status text not null default 'open' check (status in ('open','in_progress','closed')),
  assigned_to uuid references auth.users(id)
);

create or replace function private.is_staff()
returns boolean
language sql
security definer
set search_path = public
stable
as $$
  select exists (
    select 1 from public.profiles
    where user_id = (select auth.uid()) and role in ('editor','admin')
  );
$$;

create or replace function public.set_updated_at()
returns trigger language plpgsql as $$
begin new.updated_at = now(); return new; end;
$$;

drop trigger if exists stories_updated_at on public.stories;
create trigger stories_updated_at before update on public.stories for each row execute function public.set_updated_at();
drop trigger if exists tickets_updated_at on public.support_tickets;
create trigger tickets_updated_at before update on public.support_tickets for each row execute function public.set_updated_at();

alter table public.profiles enable row level security;
alter table public.stories enable row level security;
alter table public.page_views enable row level security;
alter table public.support_tickets enable row level security;

create policy "Users can read their own profile" on public.profiles for select to authenticated using ((select auth.uid()) = user_id);
create policy "Published stories are public" on public.stories for select to anon, authenticated using (status = 'published');
create policy "Staff can read every story" on public.stories for select to authenticated using ((select private.is_staff()));
create policy "Staff can create stories" on public.stories for insert to authenticated with check ((select private.is_staff()));
create policy "Staff can update stories" on public.stories for update to authenticated using ((select private.is_staff())) with check ((select private.is_staff()));
create policy "Admins can delete stories" on public.stories for delete to authenticated using ((select private.is_staff()));
create policy "Anyone can record a page view" on public.page_views for insert to anon, authenticated with check (true);
create policy "Staff can read page views" on public.page_views for select to authenticated using ((select private.is_staff()));
create policy "Anyone can create a support ticket" on public.support_tickets for insert to anon, authenticated with check (status = 'open');
create policy "Staff can read tickets" on public.support_tickets for select to authenticated using ((select private.is_staff()));
create policy "Staff can update tickets" on public.support_tickets for update to authenticated using ((select private.is_staff())) with check ((select private.is_staff()));

grant usage on schema public to anon, authenticated;
grant usage on schema private to authenticated;
grant execute on function private.is_staff() to authenticated;
grant select on public.stories to anon;
grant select, insert, update, delete on public.stories to authenticated;
grant insert on public.page_views to anon, authenticated;
grant select on public.page_views to authenticated;
grant insert on public.support_tickets to anon, authenticated;
grant select, update on public.support_tickets to authenticated;
grant select on public.profiles to authenticated;
grant usage, select on all sequences in schema public to anon, authenticated;

-- AFTER creating the admin in Authentication > Users, run this with the real UUID:
-- insert into public.profiles (user_id, role, display_name)
-- values ('PASTE-AUTH-USER-UUID-HERE', 'admin', 'Your Name');
